Opprydding i readme og legg til nyttig info og klargjeringar
navikt/teamdokumenthandtering-avro-schemas pull request #2
Opened 2021-12-15 09:06 UTC by avoldsund

2021-12-15 09:22 UTC, JohanAanesen commented
Ser fint ut :)

2021-12-15 11:54 UTC, JoakimBor approved these changes
Lettlest og godt forklart

2021-12-15 13:32 UTC, joakibj requested changes
Synes det er veldig bra at vi forbedrer dokumentasjon jevnlig

2021-12-15 13:32 UTC, joakibj commented on README.md
>  			<id>github</id>
```suggestion
			<id>dok-github</id>
```
Kan hende konsument vil ha flere id?

2021-12-15 13:32 UTC, joakibj commented on README.md
> +        <version>...</version>
Hvor finner jeg siste versjon? Kan dette auto oppdateres i en banner fra github workflow? 🤔 
Eller bare auto oppdateres er ved en release?

2021-12-15 13:32 UTC, joakibj commented on README.md
> +# Local setup
```suggestion
# Lokalt oppsett
```

2021-12-15 13:32 UTC, joakibj commented on README.md
> +## Oppsett for å kunne bruke Avroskjemaene i din applikasjon
Avro-skjema eller Avroskjema?

2021-12-15 13:32 UTC, joakibj commented on README.md
> +Neste steg er å sette opp `GITHUB_USERNAME` and `GITHUB_TOKEN` i enviroment variables. Disse verdiene må bli generert via [Github Personal Access Token](https://github.com/settings/tokens) med `SSO e
```suggestion
Neste steg er å sette opp `GITHUB_USERNAME` and `GITHUB_TOKEN` som miljøvariabler. Disse verdiene må bli generert via [Github Personal Access Token](https://github.com/settings/tokens) med `SSO enabled` og `read:packages=true`.
```

2021-12-16 06:38 UTC, avoldsund commented on README.md
> +## Oppsett for å kunne bruke Avroskjemaene i din applikasjon
Begge går nok, men Avro-skjema er sikkert greiast å skrive konsekvent, ja 👍  I fix

2021-12-16 08:48 UTC, avoldsund commented on README.md
>  			<id>github</id>
Gjorde eit forsøk på å rydde opp i dette. Topp viss du ser over det, sidan eg ikkje har stålkontroll på det :)

2021-12-16 08:58 UTC, avoldsund commented on README.md
> +        <version>...</version>
La inn lenke over til siste versjon. Prøvde å søkje litt etter det, men fann ikkje ein god måte å autoppdatere det på sparket!

2021-12-17 13:14 UTC, merged